apiVersion: v1
kind: Service
metadata:
  name: bookcatalogue
  namespace: bookcatalogue
  labels:
    app.kubernetes.io/created-by: eks-workshop
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bookcatalogue
    app.kubernetes.io/instance: bookcatalogue
    app.kubernetes.io/component: service
