apiVersion: v1
kind: Service
metadata:
  name: bookrecommendation
  namespace: bookrecommendation
  labels:
    app.kubernetes.io/created-by: eks-workshop
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bookrecommendation
    app.kubernetes.io/instance: bookrecommendation
    app.kubernetes.io/component: service
